// Copyright (C) 2026 Stacks Open Internet Foundation
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

//! Frozen execution fingerprints generated by the unchanged full-JSON loader at
//! 3fd5d990f4d53562dd1def3eb7849ae801c2d807. Each fingerprint covers every public
//! boot function with two argument sets: return value or error, assets, events,
//! execution cost, and remaining VM memory. Compare these in addition to the
//! eager-versus-selective tests, which share the selective loader's storage code.
//!
//! # Reproducing the historical baseline
//!
//!
//! The fixture keeps compact fingerprints. Set `CONTRACT_STORAGE_BASELINE_OUTPUT`
//! to dump the complete per-function observations and `fingerprints.json`, even if
//! the final comparison fails. Dump both implementations and diff the JSON for the
//! contract named by the failure. Errors, asset entries and events currently use
//! Rust Debug representations: a formatting-only change can change a fingerprint;
//! inspect the observations before accepting it as a behavioral change.
//!
//! From the repository root, create a source-only checkout of the recorded baseline
//! (or the merge base when deliberately updating the reference), copy only the test
//! harness and its inputs, and register those test modules:
//!
//! ```sh
//! baseline_checkout="$(mktemp -d)/stacks-baseline"
//! git worktree add --detach "$baseline_checkout" 3fd5d990f4d53562dd1def3eb7849ae801c2d807
//! cp stackslib/src/clarity_vm/tests/contract_storage_baseline.{rs,json} \
//!    stackslib/src/clarity_vm/tests/contract_storage_fixtures.rs \
//!    "$baseline_checkout/stackslib/src/clarity_vm/tests/"
//! cat >> "$baseline_checkout/stackslib/src/clarity_vm/tests/mod.rs" <<'MODULES'
//! mod contract_storage_baseline;
//! mod contract_storage_fixtures;
//! MODULES
//! ```
//!
//! Run this in that checkout, using an absolute output path:
//!
//! ```sh
//! CONTRACT_STORAGE_BASELINE_OUTPUT=/tmp/contracts-original \
//!   cargo nextest run -p stackslib --lib -E 'test(boot_execution_matches_original_json_loader)'
//! ```
//!
//! Run the same command in the modified checkout with a different output directory,
//! then compare the observations:
//!
//! ```sh
//! diff -ru /tmp/contracts-original /tmp/contracts-modified
//! ```
//!
//! If updating the reference intentionally, copy **only the original checkout's**
//! `fingerprints.json` into `contract_storage_baseline.json` after reviewing these
//! differences, and update the recorded commit here and in the test. No chainstate
//! snapshot or running node is needed for this harness.

use std::collections::BTreeMap;

use clarity::vm::contexts::OwnedEnvironment;
use clarity::vm::costs::{ExecutionCost, LimitedCostTracker};
use clarity::vm::database::sqlite::MemoryBackingStore;
use clarity::vm::database::{ClarityDatabase, ClaritySerializable};
use clarity::vm::test_util::{TEST_BURN_STATE_DB, TEST_HEADER_DB};
use clarity::vm::types::QualifiedContractIdentifier;
use clarity::vm::SymbolicExpression;
use stacks_common::consts::CHAIN_ID_TESTNET;
use stacks_common::types::StacksEpochId;
use stacks_common::util::hash::Sha512Trunc256Sum;

use super::contract_storage_fixtures::{boot_contracts, sample_argument};

#[test]
fn boot_execution_matches_original_json_loader() {
    // Set this only to an output directory: never overwrite the fixture in-place.
    // Use the unchanged baseline checkout to generate reference observations.
    let dump = std::env::var_os("CONTRACT_STORAGE_BASELINE_OUTPUT").map(std::path::PathBuf::from);
    if let Some(path) = &dump {
        std::fs::create_dir_all(path).unwrap();
    }
    let mut summaries = BTreeMap::new();
    for epoch in [
        StacksEpochId::Epoch22,
        StacksEpochId::Epoch33,
        StacksEpochId::Epoch34,
        StacksEpochId::Epoch40,
    ] {
        let contracts = boot_contracts();

        let mut store = MemoryBackingStore::new();
        let mut db = ClarityDatabase::new(&mut store, &TEST_HEADER_DB, &TEST_BURN_STATE_DB);
        db.begin();
        db.set_clarity_epoch_version(epoch).unwrap();
        db.commit().unwrap();
        let mut env = OwnedEnvironment::new_free(false, CHAIN_ID_TESTNET, db, epoch);
        for (name, source, version) in contracts {
            env.initialize_versioned_contract(
                QualifiedContractIdentifier::local(name).unwrap(),
                version,
                source,
                None,
            )
            .unwrap();
        }
        drop(env);
        for (name, _, _) in contracts {
            let id = QualifiedContractIdentifier::local(name).unwrap();
            let mut db = store.as_clarity_db();
            db.begin();
            let contract = db.get_contract(&id).unwrap();
            // Enumerate via the historical JSON shape so this harness compiles
            // unchanged with either representation of ContractContext.
            let json: serde_json::Value =
                serde_json::from_str(&ClaritySerializable::serialize(&*contract)).unwrap();
            let names = json["contract_context"]["functions"].as_object().unwrap();
            db.roll_back().unwrap();
            drop(db);
            let mut observations = BTreeMap::new();
            for function in names.keys() {
                let definition = contract.lookup_function(function).unwrap();
                if !definition.is_public() {
                    continue;
                }
                for nonzero in [false, true] {
                    let args: Vec<_> = definition
                        .arg_types()
                        .iter()
                        .map(|ty| SymbolicExpression::atom_value(sample_argument(ty, nonzero)))
                        .collect();
                    let mut db =
                        ClarityDatabase::new(&mut store, &TEST_HEADER_DB, &TEST_BURN_STATE_DB);
                    db.begin();
                    let mut env = OwnedEnvironment::new_cost_limited(
                        false,
                        CHAIN_ID_TESTNET,
                        db,
                        LimitedCostTracker::new_with_limit(epoch, ExecutionCost::max_value()),
                        epoch,
                    );
                    let result = env.execute_transaction(
                        id.issuer.clone().into(),
                        None,
                        id.clone(),
                        function,
                        &args,
                    );
                    let outcome = match result {
                        Ok((value, assets, events)) => {
                            let assets: BTreeMap<_, BTreeMap<_, _>> = assets
                                .to_table()
                                .into_iter()
                                .map(|(principal, entries)| {
                                    (
                                        principal.to_string(),
                                        entries
                                            .into_iter()
                                            .map(|(asset, value)| {
                                                (asset.to_string(), format!("{value:?}"))
                                            })
                                            .collect(),
                                    )
                                })
                                .collect();
                            serde_json::json!({"value": value, "assets": assets, "events": format!("{events:?}")})
                        }
                        Err(error) => serde_json::json!({"error": format!("{error:?}")}),
                    };
                    let cost = env.get_cost_total();
                    let (mut db, tracker) = env.destruct().unwrap();
                    let memory = tracker.get_memory();
                    db.roll_back().unwrap();
                    observations.insert(
                        format!("{function}/{nonzero}"),
                        serde_json::json!({"outcome": outcome, "cost": cost, "memory": memory}),
                    );
                }
            }
            if let Some(path) = &dump {
                std::fs::write(
                    path.join(format!("{epoch:?}-{name}.json")),
                    serde_json::to_vec_pretty(&observations).unwrap(),
                )
                .unwrap();
            }
            let bytes = serde_json::to_vec(&observations).unwrap();
            summaries.insert(format!("{epoch:?}/{name}"), serde_json::json!({"cases": observations.len(), "sha512_256": Sha512Trunc256Sum::from_data(&bytes).to_string()}));
        }
    }
    if let Some(path) = &dump {
        std::fs::write(
            path.join("fingerprints.json"),
            serde_json::to_vec_pretty(&summaries).unwrap(),
        )
        .unwrap();
    }
    let expected: BTreeMap<String, serde_json::Value> =
        serde_json::from_str(include_str!("contract_storage_baseline.json")).unwrap();
    assert_eq!(summaries.len(), expected.len());
    for (case, actual) in summaries {
        assert_eq!(
            Some(&actual),
            expected.get(&case),
            "full-JSON baseline changed for {case}; set CONTRACT_STORAGE_BASELINE_OUTPUT to dump per-case observations (see docs/clarity/contract-storage.md)"
        );
    }
}
