[workspace]
resolver = "2"
members = [
    "stackslib",
    "stacks-common",
    "pox-locking",
    "clarity-types",
    "clarity",
    "stx-genesis",
    "libstackerdb",
    "libsigner",
    "stacks-signer",
    "stacks-node",
    "stacks-bench",
    "stacks-profiler",
    "stacks-profiler-macros",
    "contrib/stacks-inspect",
    "contrib/stacks-cli"
]

exclude = ["contrib/tools/config-docs-generator"]

# Dependencies we want to keep the same between workspace members
[workspace.dependencies]
# Local dependencies
stacks-profiler = { path = "stacks-profiler" }

# External dependencies
ed25519-dalek = { version = "2.1.1", default-features = false }
hashbrown = { version = "0.15.2", features = ["serde"] }
lazy_static = "1.4.0"
rand_core = "0.6.4"
rand = "0.8"
rand_chacha = "0.3.1"
serde = "1"
serde_derive = "1"
serde_json = { version = "1.0", features = ["arbitrary_precision", "unbounded_depth"] }
slog = { version = "2.5.2", features = [ "max_level_trace" ] }
rusqlite = { version = "0.31.0", features = ["blob", "serde_json", "i128_blob", "bundled", "trace"] }
tikv-jemallocator = "0.5.4"
thiserror = "1.0.65"
toml = "0.5.6"
clap = { version = "4.5.53", default-features = false, features = ["std", "derive", "color", "help", "usage", "error-context", "suggestions"] }
anyhow = { version = "1.0.100", default-features = false }
tempfile = { version = "3.23.0", default-features = false, features = ["getrandom"] }
diesel = { version = "2.3.4", default-features = false, features = ["sqlite", "returning_clauses_for_sqlite_3_35", "chrono", "32-column-tables", "serde_json"] }
diesel_migrations = { version = "2.3.1", default-features = false, features = ["sqlite"] }
diesel-async = { version = "0.7.4", default-features = false, features = ["sqlite", "migrations", "bb8"] }
reflink-copy = { version = "0.1.28", default-features = false }
ignore = { version = "0.4.25", default-features = false }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
libc = { version = "0.2.178", default-features = false }
syn = { version = "2.0.111", default-features = false, features = ["full", "extra-traits"] }
quote = { version = "1.0.42", default-features = false, features = ["proc-macro"] }
proc-macro2 = { version = "1.0.103", default-features = false, features = ["proc-macro", "span-locations"] }
darling = { version = "0.23.0", default-features = false, features = ["suggestions"] }
chrono = { version = "0.4.42", default-features = false, features = ["serde"] }
sha2 = { version = "0.10.9", default-features = false }
bollard = { version = "0.19.4", default-features = false, features = ["http", "pipe"] }
tokio = { version = "1.48.0", default-features = false, features = ["signal", "macros", "rt-multi-thread", "rt"] }
futures = { version = "0.3.31", default-features = false }
criterion = { version = "0.8.1", default-features = false, features = ["html_reports"] }
cliclack = { version = "0.3.7", default-features = false }
console = { version = "0.16.2", default-features = false, features = ["std", "unicode-width", "ansi-parsing"] }


# Use a bit more than default optimization for
# dev builds to speed up test execution
[profile.dev]
opt-level = 1

# Use release-level optimization for dependencies
# This slows down "first" builds on development environments,
# but won't impact subsequent builds.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true
codegen-units = 1
lto = "fat"

# Release build with less LTO
# Useful for faster builds or low-RAM environments
[profile.release-lite]
inherits = "release"
lto = "thin"

# faster tests for `insta` https://docs.rs/insta/1.43.2/insta/#optional-faster-runs
[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
